### ISSUE TITLE
Bug in index.html

### ISSUE THREAD

**Issue by anshshrivastava0707** [beginner-cryptonyx/Study-Page#2]
Hello, I have encountered a bug in your website, on downloading the source files and running index.html, the nav buttons don't work properly, they take you to the page you are supposed to be in, but don' activate the tabs

**Comment by beginner-cryptonyx** [comment]
Hi @Immortal-youtube, The error you are facing is because of the `CORS` policy that many new browsers have. You are running the file locally on machine, try running it on a server, (local will work).
